SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `Locations`;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE `Locations`(
`ID` INT NOT NULL AUTO_INCREMENT,
`Name` VARCHAR(255),
`Continent` VARCHAR(255),
`Slave` TINYINT,
UNIQUE(`Name`),
PRIMARY KEY(`ID`)
)ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `Houses`;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE `Houses`(
`ID` INT NOT NULL AUTO_INCREMENT,
`Name` VARCHAR(255) NOT NULL,
`Motto` VARCHAR(255),
`Sigil` VARCHAR(255),
`LocationID` INT,
UNIQUE(`Name`),
PRIMARY KEY(`ID`),
FOREIGN KEY(`LocationID`) REFERENCES `Locations`(ID)
	ON DELETE SET NULL
)ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `Characters`;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE `Characters`(
`ID` INT NOT NULL AUTO_INCREMENT,
`Name` VARCHAR(255) NOT NULL,
`HouseID` INT,
`Birthplace` INT,
`Biography` VARCHAR(255),
UNIQUE(`Name`),
PRIMARY KEY(`ID`),
FOREIGN KEY(`HouseID`) REFERENCES `Houses`(ID)
	ON DELETE SET NULL,
FOREIGN KEY(`Birthplace`) REFERENCES `Locations`(ID)
	ON DELETE SET NULL
)ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `Episodes`;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE `Episodes`(
`ID` INT NOT NULL AUTO_INCREMENT,
`Season`  INT NOT NULL,
`Season_ep` INT NOT NULL,
`Title` VARCHAR(255) NOT NULL,
`Air_Date` DATE NOT NULL,
UNIQUE(`Season`, `Season_ep`),
PRIMARY KEY(`ID`)
)ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `Appearances`;
SET FOREIGN_KEY_CHECKS=1;

CREATE TABLE `Appearances`(
`EpisodeID` INT NOT NULL,
`CharacterID` INT NOT NULL,
PRIMARY KEY(`EpisodeID` , `CharacterID`),
FOREIGN KEY(`EpisodeID`) REFERENCES `Episodes`(ID)
	ON DELETE CASCADE,
FOREIGN KEY(`CharacterID`) REFERENCES `Characters`(ID)
	ON DELETE CASCADE
)ENGINE=InnoDB;
